### ISSUE TITLE
PI Installer: Advanced Menus

### ISSUE THREAD

**Issue by rgleason** [leamas/OpenCPN#1]
I find there is something about the  PI Installer menus that could be improved, but I am not sure how or what to suggest, perhaps it is related to being clear about what the current URL does or can do.  If they could be simplified, by not having multiple menus open, and more condensed, that might help small screen formats. For discussion.

Screen 1
![PI-Installer-Screen-1](https://user-images.githubusercontent.com/2363959/70856701-73da0700-1eaf-11ea-9a7f-53fae3c6088c.png)

Screen 2
![PI-Installer-Screen-2](https://user-images.githubusercontent.com/2363959/70856704-789ebb00-1eaf-11ea-89f4-82782506f748.png)

Screen 3
![PI-Installer-Screen-3](https://user-images.githubusercontent.com/2363959/70856708-86544080-1eaf-11ea-9ab4-8f68c22efdd6.png)

**Comment by rgleason** [comment]
HakanSV wrote:
Rick..
Another example from OpenPlotter if you haven't seen it. Just to compare.

![Openplotter](https://user-images.githubusercontent.com/2363959/70862758-6869f880-1f0e-11ea-8dcc-a6f536b6a381.png)

**Comment by rgleason** [comment]
Alec wrote: 
> Also note that the OpenPlotter example is not really comparable to Rick's screenshot. Openplotter's is about updating plugins, Rick's is about updating the catalog i. e. the list of candidates.

**Comment by leamas** [comment]
The smllest window should not be visible when displaying the Advanced Catalog Manager.

**Comment by leamas** [comment]
moving back to opencpn...
