### ISSUE TITLE
PI Installer: Options > Plugins - Provide indication to differentiate old and new plugins.

### ISSUE THREAD

**Issue by rgleason** [leamas/OpenCPN#2]
When there is a good opportunity.

Also wouldn't it be helpful to show the path to the plugin?

**Comment by rgleason** [comment]
Alec wrote:
Right.

But first: the installer is not part of opencpn. Please file issues at https://github.com/leamas/opencpn/issues instead, and close the issues here.

Also: see #1457 (comment) and #1457 (comment).

**Comment by leamas** [comment]
> Also wouldn't it be helpful to show the path to the plugin?

Why? All sorts of problems will arise  if users starts messing with the files directly. If there is such a need, my instinct says there is a bug somewhere to fix...

Are you aware of paths to other plugins, for example those in the browser?

**Comment by rgleason** [comment]
Nope. Ok for me not to show path. It would be nice to know what is an old PI and what is new, to help users know which older PI to remove manually as they get updated new ones.
